### ISSUE TITLE
setup repository 

### ISSUE THREAD

**Issue by gschwend** [linea-it/sky-viewer#1]
```[tasklist]
### Tasks
- [ ] https://github.com/linea-it/science_server/issues/3
- [ ] Install uWSGI
- [x] Configure devcontainer
- [x] Configure Pre Commit
- [ ] https://github.com/linea-it/science_server/issues/8
- [ ] https://github.com/linea-it/science_server/issues/4
- [x] install Ngnix as a proxy
```
